Innovatec/Controllers/BasculasController.cs
using Innovatec.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Innovatec.Controllers
{
    public class BasculasController : Controller
    {
        DB_I4 db = new DB_I4();
        // GET: Basculas
        public ActionResult Index()
        {
            var List = db.tBasculas.AsEnumerable();
            return View(List);
        }
        public JsonResult List()
        {
            var List = from b in db.tBasculas.AsEnumerable()
                             select new
                             {
                                 b.ID_Bascula,
                                 Ubicacion = b.Descripcion.Split(':')[0],
                                 Status = b.Descripcion.Split(':')[1]
                             };
            
            return Json(List, JsonRequestBehavior.AllowGet);
        }

        // GET: Basculas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Basculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Basculas/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Basculas/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Basculas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Basculas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Basculas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Innovatec/Views/Basculas/Index.cshtml
@model IEnumerable<Innovatec.Models.tBasculas>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*@section head{
    <meta http-equiv="Refresh" content="5" />
}*@

<div class="container mb-5">
    <h2 style="color:#bfe8e4">Basculas</h2>

    <table class="table table-bordered">
        <thead style="color:#fff">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID_Bascula)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>
        <tbody style="color:#fff; background-color:#000">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_Bascula)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion.Split(':')[0])
                    </td>
                    <td>
                        @if (item.Descripcion.Split(':')[1] != "Active")
                        {
                            <text>
                                <i style="color:#ff7e96" class="fa fa-window-close-o" aria-hidden="true"></i>
                            </text>
                        }
                        else
                        {
                            <text>
                                <i style="color:aquamarine" class="fa fa-check-square-o" aria-hidden="true"></i>
                            </text>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div style="width:100%; margin-bottom:150px"></div>
@section scripts{
    <script>
        var table = $('.table').DataTable({
                ajax: {
                     url: '@Url.Action("List","Basculas")',
                     dataSrc: ''
                },
                columns: [
                    { data: 'ID_Bascula' },
                    { data: 'Ubicacion' },
                    {
                        data: 'Status',
                        render: function (data, type, row) {
                            if (data != "Active") {
                                return '<i style = "color:#ff7e96" class="fa fa-window-close-o" aria-hidden="true" ></i>';
                            }
                            else {

                                return '<i style = "color:aquamarine" class="fa fa-check-square-o" aria-hidden="true" ></i>';
                            }
                        }
                    }
                 ],
                 drawCallback: function (settings) {
                     $('tr').addClass('bg-dark')
                     $('.dataTables_length').attr("style", "color:#fff")
                     $('.dataTables_filter').attr("style", "color:#fff")
                     $('[aria-controls="DataTables_Table_0"]').attr("style", "color:#fff")
                 }
             });
        $(document).ready(function () {
            setInterval(function () {
                table.ajax.reload();
            }, 1000);
        });
    </script>
}