Innovatec/Controllers/LineasComponentesBasculasController.cs
using Innovatec.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Innovatec.Class;
using System.Web.Routing;
using System.Threading.Tasks;
using System.Threading;
using System.IO;

namespace Innovatec.Controllers
{
    public class LineasComponentesBasculasController : Controller
    {
        DB_I4 db = new DB_I4();
        // GET: LineasComponentesBasculas
        public ActionResult Index()
        {
            var List = db.tLineasComponentesBasculas.AsEnumerable();
            return View(List);
        }
        public JsonResult List()
        {
            var List = from lcb in db.tLineasComponentesBasculas.AsEnumerable()
                       select new
                       {
                           Bascula = lcb.ID_Bascula,
                           Componente = lcb.tComponentes.Descripcion,
                           Linea = lcb.tLineasProduccion.Descripcion,
                           Cantidad = lcb.Cantidad,
                           Error = (lcb.Cantidad >= lcb.Maximo) ? "Componente llego a su Maximo."
                                     : (lcb.Cantidad <= lcb.Minimo) ? "Componente llego a su Minimo."
                                     : ""
                       };
            List<Thread> LT = new List<Thread>();
            
            foreach (var item in List.Where(l => !String.IsNullOrEmpty(l.Error)))
            {
                string area = item.Linea.Split(new char[] { '_' }).FirstOrDefault();
                string home = Url.Action("Index", "Home",
                                            routeValues: new RouteValueDictionary(new { }), protocol: "http",
                                            hostName: Request.Url.DnsSafeHost);
                string carpeta = HttpContext.Server.MapPath("/Views/Emails");
                LT.Add(new Thread(() => SendNotifcations(home, carpeta,item.Componente, "jehusiqueiros@gmail.com", area)));
            }
            for (int i = 0; i < LT.Count(); i++)
            {
                LT[i].Start();
            }
            
            return Json(List, JsonRequestBehavior.AllowGet);
        }

        public void SendNotifcations(string home, string carpeta, string componente, string destinatario, string area) {
        Email Email = new Email();
            switch (area.ToLower())
            {
                case "almacen":
                    Email.Selector(home, Path.Combine( carpeta, "Almacen.html"),componente, destinatario);
                    Class.Telegram.Send_Message(componente, "proveedor").GetAwaiter();
                    Task Wait = new Task(() => Class.Telegram.Waiter(3));
                    Wait.Start();
                    Task.WaitAll(Wait);

                    break;
                case "linea":
                    Email.Selector(home, Path.Combine(carpeta, "Linea.html"), componente, destinatario);
                    Class.Telegram.Send_Message(componente, "almacen").GetAwaiter();
                    Task Wait2 = new Task(() => Class.Telegram.Waiter(3));
                    Wait2.Start();
                    Task.WaitAll(Wait2);
                    break;
            }
        }

        // GET: LineasComponentesBasculas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LineasComponentesBasculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LineasComponentesBasculas/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LineasComponentesBasculas/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LineasComponentesBasculas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LineasComponentesBasculas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LineasComponentesBasculas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Innovatec/Views/LineasComponentesBasculas/Index.cshtml
@model IEnumerable<Innovatec.Models.tLineasComponentesBasculas>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
}

<div class="container mb-5">
    <h2 style="color:#bfe8e4">Inventario</h2>

    <table class="table table-bordered">
        <thead class="bg-dark">
            <tr>
                <th>
                    BASCULA
                </th>
                <th>
                    COMPONENTE
                </th>
                <th>
                    LINEA
                </th>
                <th>
                    CANTIDAD
                </th>
                <th>
                    ERROR
                </th>
            </tr>
        </thead>
        <tbody style="color:#fff; background-color:#000">
            @foreach (var item in Model)
            {
                <tr style="color:#fff;
                           @{
                               var color = "background-color:#ff7e96;";
                               if (item.Cantidad  <= item.Minimo || item.Cantidad >= item.Maximo) {
                                   @color;
                               }
                           } ">
                    <td>
                        @Html.DisplayFor(modelItem => item.tBasculas.ID_Bascula)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tComponentes.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tLineasProduccion.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cantidad)
                    </td>
                    <td>
                        @{
                            if (item.Cantidad <= item.Minimo)
                            {
                                @Html.Raw("El material ha llegado a su minimo");
                            }
                            else if (item.Cantidad >= item.Maximo)
                            {
                                @Html.Raw("El material ha llegado a su maximo");
                            }
                        }
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

<div style="width:100%; margin-bottom:150px"></div>
@section scripts{
    <script>
        var table = $('.table').DataTable({
                ajax: {
                     url: '@Url.Action("List","LineasComponentesBasculas")',
                     dataSrc: ''
                },
                columns: [
                    { data: 'Bascula' },
                    { data: 'Componente' },
                    { data: 'Linea' },
                    { data: 'Cantidad' },
                    {
                        data: 'Error'
                    }
                 ],
            createdRow: function (row, data, index) {
                if (data['Error'] != "") {

                    $(row).css("background-color", "red");
                }
                else {
                    $(row).addClass('bg-dark')
                }
                },  
                 drawCallback: function (settings) {
                     $('.dataTables_length').attr("style", "color:#fff")
                     $('.dataTables_filter').attr("style", "color:#fff")
                     $('[aria-controls="DataTables_Table_0"]').attr("style", "color:#fff")
                 }
             });
        $(document).ready(function () {
            setInterval(function () {
                table.ajax.reload();
            }, 1000);
        });
    </script>
}