Innovatec/Controllers/ComponentesController.cs
using Innovatec.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Innovatec.Controllers
{
    public class ComponentesController : Controller
    {
        DB_I4 db = new DB_I4();
        // GET: Componentes
        public ActionResult Index()
        {
            var List = db.tComponentes.ToList();
            return View(List);
        }

        // GET: Componentes/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Componentes/Create
        public ActionResult Create()
        {
            tComponentes NewItem = new tComponentes();
            return View(NewItem);
        }

        // POST: Componentes/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Componentes/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Componentes/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Componentes/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Componentes/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Innovatec/Views/Componentes/Create.cshtml
@model Innovatec.Models.tComponentes

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2 style="color:#bfe8e4">Componentess</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>tComponentes</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.ID_Componente, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID_Componente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID_Componente, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.PesoUnitarioGramos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PesoUnitarioGramos, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PesoUnitarioGramos, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Minimo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Minimo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Minimo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Maximo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Maximo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Maximo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Innovatec/Views/Componentes/Index.cshtml
@model IEnumerable<Innovatec.Models.tComponentes>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <h2 style="color:#bfe8e4">Componentes</h2>

    <table class="table table-bordered">
        <thead style="color:#fff">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PesoUnitarioGramos)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Minimo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Maximo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagen)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody style="color:#fff">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PesoUnitarioGramos)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Minimo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Maximo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Imagen)
                    </td>
                    <td class="text-wa">
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID_Componente }, new { @class = "text-warning"}) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID_Componente }, new { @class = "text-info" }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID_Componente }, new { @class = "text-danger" })
                    </td>
                </tr>
            }

        </tbody>
    </table>
    <a href="@Url.Action("Create","Componentes")">Nuevo</a>
</div>